### ISSUE TITLE
RGB color game not working

### ISSUE THREAD

**Issue by Sonu0305** [you-dont-need/You-Dont-Need-JavaScript#621]
Hi @aayush105 ,
# Issue:
The **RGB color game** only has a _.html_ and a _.css_ file while in _.html_ script the creator has linked a _.js_ file which doesn't exist and hence the game doesnt work.

# **.html snippet:**
![image](https://github.com/user-attachments/assets/f8d1ecc5-13fb-4f7e-8ea0-f053b10c1ab4)

# **Folder Structure:**
![image](https://github.com/user-attachments/assets/92e8d792-e4cb-4040-930a-26692432898e)

# **Not Working Game:**
https://github.com/user-attachments/assets/c63e5e4c-f16c-4c7f-9e36-c0968bf5fea8

**Comment by xenomancy** [comment]
give me the accesss

**Comment by Sonu0305** [comment]
@xenomancy 
Issue is already solved by me in a PR #623

**Comment by acornmonkey** [comment]
That pull request was declined because it used JavaScript, so the RGB color game still doesn't work.
